### ISSUE TITLE
Old depenencies - needs to be updated

### ISSUE THREAD

**Issue by njames** [squarecloudlabs/jigsaw-clean-blog#1]
Installing this will not work currently if you are running php 8.2 and I hope you are. 

Good first issues to be able to updated the composer dependencies so that it will run on php 8.2

**Comment by p1kalys** [comment]
Hey @njames I want to work on this, please assign it to me

**Comment by njames** [comment]
Done - you are good to go :)

**Comment by njames** [comment]
Thanks @p1kalys
